from enum import Enum
from os import PathLike

PATH = str | bytes | PathLike

class IDE(Enum):
    PYCHARM = ...
    INTELLIJ_IDEA = ...
    PHPSTORM = ...
    RIDER = ...
    WEBSTORM = ...
    CLION = ...
    GOLANG = ...
    RUBYMINE = ...


def is_installed(ide: IDE) -> bool: ...


def open(ide: IDE, *paths: PATH, line: int | None = ..., column: int | None = ...) -> None: ...


def compare(ide: IDE, path1: PATH, path2: PATH, path3: PATH | None = ...) -> None: ...