from enum import Enum
from os import PathLike


class IDE(Enum):
    PYCHARM = ...
    INTELLIJ_IDEA = ...
    PHPSTORM = ...
    RIDER = ...
    WEBSTORM = ...
    CLION = ...
    GOLANG = ...
    RUBYMINE = ...


def open(ide: IDE, *paths: str | bytes | PathLike, line: int | None = ..., column: int | None = ...) -> None: ...


def is_installed(ide: IDE) -> bool: ...
